services:
  - type: web
    name: telegram-gpt-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    runtime: python3.10
    envVars:
      - key: OPENAI_API_KEY
        value: your-openai-api-key
      - key: TELEGRAM_TOKEN
        value: your-telegram-bot-token
